[project]
name = "kubernetes-rag-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AaryanBairagi", email = "aaryanbairagi11@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "fastapi>=0.141.1",
    "fonttools>=4.66.0",
    "google-generativeai>=0.8.6",
    "langchain-google-genai>=4.4.0",
    "logfire[fastapi,requests]>=5.1.1",
    "loguru>=0.7.3",
    "numpy>=2.5.3",
    "pdfplumber>=0.11.10",
    "pypdf>=6.19.0",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.3",
    "python-pptx>=1.0.2",
    "qdrant-client>=1.19.1",
    "requests>=2.34.2",
    "sentence-transformers>=6.1.0",
    "unstructured[docx,pptx]>=0.27.9",
    "uuid>=1.30",
    "uvicorn[standard]>=0.54.0",
]

[project.scripts]
kubernetes-rag-app = "kubernetes_rag_app:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
